yarnPath: "C:\\repo\\blog\\.yarn\\releases\\yarn-berry.js"
packageExtensions:
  'react-script-tag@*':
    dependencies:
      'babel-runtime': '*'
  'favicons-webpack-plugin@*':
    dependencies:
      'webpack': '*'
  '@jimp/utils@*':
    dependencies:
      'regenerator-runtime': '*'
  'react-dom-core@*':
    dependencies:
      'fbjs': '*'
